### PR TITLE
add 2 parameters in Slurm class

### PR DESCRIPTION
**Pull request by bioShaun**
1. Add log_dir parameter to specify a log_dir, default value is "logs" in current directory as before.

2. Add check_bash_var parameter to choose whether to add "set -eo pipefail -o nounset" in slurm script.
   Because "set -eo pipefail -o nounset" will exit script when I try to enter virtual environment of Python
   using virtualenvwrapper.

### CODE REVIEW

**Comment by brentp** [comment]
looks good except `check_bash_var` seems a misnomer. maybe this could be `bash_strict` or something?

**Comment by bioShaun** [comment]
> looks good except `check_bash_var` seems a misnomer. maybe this could be `bash_strict` or something?

I'm realy not goot at naming variables, `bash_strict` is a much better name.

**Comment by brentp** [comment]
thanks!

**Comment by bioShaun** [comment]
I'm working on a python pipeline using slurm to submit jobs,  `slurmpy` helps a lot.

**Pull request merged**
